[package]
name = "udata"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
jsonpath-rust = "0.7.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.124"
